version: '3.8'

services:
  deepseek-ai:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      # Монтируем папку base1 для локальной разработки
      - ./base1:/app/base1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
